import { Inter } from 'next/font/google'
import './globals.css'
import Header from './component/Header'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body ><Header>{children}</Header></body> */}
       <body ><Header>{children}</Header></body>
    </html>
  )
}
